apiVersion: apps/v1
kind: Deployment
metadata:
  name: $SERVICE_NAME
  namespace: $NAMESPACE
  labels:
    app: $SERVICE_NAME
spec:
  replicas: 2
  selector:
    matchLabels:
      run: $SERVICE_NAME
  template:
    metadata:
      labels:
        run: $SERVICE_NAME
    spec:
      containers:
        - name: $SERVICE_NAME
          image: $IMAGE
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 512Mi
            requests:
              cpu: "1"
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: $SERVICE_NAME
  namespace: $NAMESPACE
  labels:
    run: $SERVICE_NAME
spec:
  type: LoadBalancer
  selector:
    run: $SERVICE_NAME
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: $SERVICE_NAME-ingress
  namespace: $NAMESPACE
spec:
  ingressClassName: nginx
  rules:
    - host: $INGRESS_HOST
      http:
        paths:
          - backend:
              service:
                name: $SERVICE_NAME
                port:
                  number: 8080
            path: /
            pathType: Prefix
